### ISSUE TITLE
Use `be` matchers

### ISSUE THREAD

**Issue by geniou** [nevir/rubocop-rspec#16]
check for things like `eq(true)` and propose to use `be_true` / `be_truthy`

https://www.relishapp.com/rspec/rspec-expectations/v/3-0/docs/built-in-matchers/be-matchers

**Comment by ochagata** [comment]
can this be closed?

**Comment by geniou** [comment]
@ochagata I think this hasn't be done yet snd its still a valid idea. So I would love to have this one day but at the moment I don't have the time to do it on my own.

**Comment by backus** [comment]
This is a bit tough to enforce since the semantics of `#==` (backing `eq`), `#eql?` (backing `eql`), and `#equal?` (backing `be`) are all different. Specifically, `#==` generally means "comparison with coercion" so even if I write `expect(foo.bar).to eq(true)` it does not mean that either `expect(foo.bar).to eql(true)` or `expect(foo.bar).to be(true)` are certain.

I'm leaving this issue open because I need to do some thinking about how much more opinionated I would like to make rubocop-rspec. IMO if you write some object with this behavior:

```ruby
foo == true     # => true
foo.eql?(true) # => false
```

you are probably doing something weird. With that said things become more hairy if we are talking about something like `eq(1)` vs `be(1)`. I would be ok with flagging `eql(1)` -> `be(1)` since `eql?` should not involve coercion. It is totally valid though to say something like `expect(Score.new(1)).to eq(1)`
